<?php

namespace Database\Seeders;

use App\Throwable;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ThrowableSeeder extends Seeder
{
    public function run()
    {
        $throwables = [
            [
                'character_id' => 3,
                'name' => 'Impact Axe',
                'description' => 'The Impact Axe is the connoisseur choice for the dwarf of tomorrow. Compact and easy to carry, extends to full size upon throwing, and discharges a lethal burst of electricity upon impact with any living target. Can be safely retrieved by the user in case of bad aim.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":8},"ex2":{"name":"Direct Damage","value":160},"ex3":{"name":"Area Damage","value":80},"ex4":{"name":"AoE Radius","value":1.4},"ex5":{"name":"Stun Chance","value":100,"percent":true},"ex6":{"name":"Stun Duration","value":1.5},"ex7":{"name":"Retrievable","value":1,"boolean":true}}',
                'credits_cost' => 0,
                'magnite_cost' => 0,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 0,
                'icon' => 'D_T1_Axe',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 3,
                'name' => 'High Explosive Grenade',
                'description' => 'A standard high-explosive grenade with a medium kill radius. Can be used to remove dirt or bugs or both.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":6},"ex2":{"name":"Fuse Time","value":1.7},"ex3":{"name":"Area Damage","value":140},"ex4":{"name":"AoE Radius","value":4.3},"ex5":{"name":"Armor Breaking","value":400,"percent":true},"ex6":{"name":"Fear Factor","value":100,"percent":true}}',
                'credits_cost' => 1200,
                'magnite_cost' => 0,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 10,
                'icon' => 'D_T2_He',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 3,
                'name' => 'Neurotoxin Grenade',
                'description' => 'Releases a cloud of slow-acting toxins engineered to exclusively affect life indigenous to Hoxxes IV. WARNING: HIGHLY FLAMMABLE!',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":4},"ex2":{"name":"Fuse Time","value":2.5},"ex3":{"name":"Cloud Radius","value":7.5},"ex4":{"name":"Cloud Duration","value":15},"ex5":{"name":"Neurotoxin Chance","value":100,"percent":true},"ex6":{"name":"Neurotoxin Avg DPS","value":12},"ex7":{"name":"Neurotoxin Movespeed Slow","value":-30,"percent":true},"ex8":{"name":"Neurotoxin Duration","value":30}}',
                'credits_cost' => 3400,
                'magnite_cost' => 0,
                'bismor_cost' => 20,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 0,
                'icon' => 'D_T3_Neuro',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 1,
                'name' => 'L.U.R.E.',
                'description' => 'This Laser Utility Refraction Emitter - or L.U.R.E for short - projects a handsome hologram that will attract all nearby enemies. Be mindful to keep your distance - once the onboard shielding fails, it will unleash a devastating electrical charge.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":4},"ex2":{"name":"Fuse Time","value":1.5},"ex3":{"name":"Dance Duration","value":20},"ex4":{"name":"Health","value":50},"ex5":{"name":"Area Damage","value":20},"ex6":{"name":"AoE Radius","value":2.5},"ex7":{"name":"Electrocute Chance","value":100,"percent":true},"ex8":{"name":"Electrocute DPS","value":12},"ex9":{"name":"Electrocute Duration","value":3}}',
                'credits_cost' => 0,
                'magnite_cost' => 0,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 0,
                'icon' => 'E_T1_Lure',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 1,
                'name' => 'Plasma Burster',
                'description' => 'The Plasma Burster does more or less what you\'d expect from the name. It releases 4 bursts of scorching plasma in rapid succession upon being thrown. Keep away from beards at all costs.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":6},"ex2":{"name":"Number of Detonations","value":4},"ex3":{"name":"Delay between Detonations","value":0.45},"ex4":{"name":"Area Damage","value":60},"ex5":{"name":"AoE Radius","value":3.5},"ex6":{"name":"Fear Factor","value":100,"percent":true}}',
                'credits_cost' => 1200,
                'magnite_cost' => 0,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 10,
                'icon' => 'E_T2_Plasma',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 1,
                'name' => 'Proximity Mine',
                'description' => 'A timeless classic. Sticks to any surface and explodes shortly after an enemy enters its trigger area. And if it fails to find a target, it can be safely disarmed and retrieved. Note: proximity trigger requires a few seconds for calibration.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":4},"ex2":{"name":"Initial Arming Time","value":3},"ex3":{"name":"Trigger Radius","value":4},"ex4":{"name":"Explosion Delay after Triggering","value":1},"ex5":{"name":"Area Damage","value":110},"ex6":{"name":"AoE Radius","value":5},"ex7":{"name":"Fear Factor","value":100,"percent":true},"ex8":{"name":"Arming Time after Explosion","value":1},"ex9":{"name":"Number of Detonations","value":4},"ex10":{"name":"Lifetime after first Detonation","value":180}}',
                'credits_cost' => 3400,
                'magnite_cost' => 0,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 20,
                'jadiz_cost' => 0,
                'icon' => 'E_T3_Proximity',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 4,
                'name' => 'Sticky Grenade',
                'description' => 'Will stick to any surface or creature, and then explode after a short time. Sometimes keeping it simple is best.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":6},"ex2":{"name":"Impact Direct Damage","value":20},"ex3":{"name":"Impact Fear Factor","value":250,"percent":true},"ex4":{"name":"Fuse Time","value":2},"ex5":{"name":"Explosion Direct Damage","value":90},"ex6":{"name":"Explosion Area Damage","value":130},"ex7":{"name":"AoE Radius","value":4},"ex8":{"name":"Explosion Fear Factor","value":100,"percent":true}}',
                'credits_cost' => 0,
                'magnite_cost' => 0,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 0,
                'icon' => 'G_T1_Sticky',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 4,
                'name' => 'Incendiary Grenade',
                'description' => 'One of our most popular "handle with care" items. Will explode on activation, covering a large area in roaring fire. Would almost be cozy if the flames did not burn hot enough to melt steel.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":4},"ex2":{"name":"Area Heat","value":100},"ex3":{"name":"AoE Heat Radius","value":3.5},"ex4":{"name":"Flames Radius","value":4.3},"ex5":{"name":"Flames Avg DPS","value":13.33},"ex6":{"name":"Flames Heat/sec","value":25},"ex7":{"name":"Flames Duration","value":6}}',
                'credits_cost' => 1200,
                'magnite_cost' => 10,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 0,
                'icon' => 'G_T2_Incendiary',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 4,
                'name' => 'Cluster Grenade',
                'description' => 'When one grenade just won\'t cut it. This thing is basically Armageddon in the palm of your hand.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":4},"ex2":{"name":"Fuse Time","value":1.2},"ex3":{"name":"Bomblets","value":9},"ex4":{"name":"Bomblet Area Damage","value":40},"ex5":{"name":"Bomblet AoE Radius","value":3.85},"ex6":{"name":"Stun Chance","value":50,"percent":true},"ex7":{"name":"Stun Duration","value":1.5}}',
                'credits_cost' => 3400,
                'magnite_cost' => 0,
                'bismor_cost' => 0,
                'umanite_cost' => 20,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 0,
                'icon' => 'G_T3_Cluster',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 2,
                'name' => 'Inhibitor-Field Generator',
                'description' => 'The IFG - or Inhibitor-Field Generator - is one of the latest inventions of the good people down in R&D. Toss one of these bad boys into a cluster of bugs, and watch them slow right down. Enemies affected by the IFG field also take amplified damage from all sources.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":6},"ex2":{"name":"AoE Radius","value":3},"ex3":{"name":"AoE Duration","value":15},"ex4":{"name":"Damage Amplification","value":130,"percent":true},"ex5":{"name":"Movespeed Slow","value":-75,"percent":true}}',
                'credits_cost' => 0,
                'magnite_cost' => 0,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 0,
                'icon' => 'S_T1_IFG',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 2,
                'name' => 'Cryo Grenade',
                'description' => 'Instantly lowers the ambient temperature of everything in a medium-sized area. Will flash-freeze most Hoxxes wildlife - as well as any helpless DRG employees caught in the blast zone.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":4},"ex2":{"name":"Fuse Time","value":1.2},"ex3":{"name":"Area Cold","value":250},"ex4":{"name":"AoE Radius","value":6}}',
                'credits_cost' => 1200,
                'magnite_cost' => 10,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 0,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 0,
                'icon' => 'S_T2_Freeze',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'character_id' => 2,
                'name' => 'Pheromone Canister',
                'description' => 'Any creature covered by the substance within becomes an irresistible target to any kind of Hoxxes wildlife. Handle with extreme care. The boys in R&D are very proud of this one.',
                'json_stats' => '{"ex1":{"name":"Carried Amount","value":4},"ex2":{"name":"Effect Radius","value":4},"ex3":{"name":"Enemies within Radius Afflicted","value":50,"percent":true},"ex4":{"name":"Pheromone Attack Cost Modifier","value":12},"ex5":{"name":"Pheromone Movepseed Slow","value":-10,"percent":true},"ex6":{"name":"Pheromone Duration","value":15}}',
                'credits_cost' => 3400,
                'magnite_cost' => 0,
                'bismor_cost' => 0,
                'umanite_cost' => 0,
                'croppa_cost' => 20,
                'enor_pearl_cost' => 0,
                'jadiz_cost' => 0,
                'icon' => 'S_T3_Pheremone',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ];
        Throwable::insert($throwables);
    }
}
