<?php

use App\Throwable;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ThrowableSeeder extends Seeder
{
    public function run()
    {
        // Seed as of 7/1/2020
        $throwables = [ 
           ['character_id' => 3, 'name' => 'Impact Axe', 'description' => 'The Impact Axe is the connoisseur choice for the dwarf of tomorrow. Compact and easy to carry, extends to full size upon throwing, and discharges a lethal burst of electricity upon impact with any living target. Can be safely retrieved by the user in case of bad aim.', 'json_stats' => '{"Direct Damage": 80, "Area Damage": 160, "AoE Radius": "1.4m", "Carried Amount": 8}', 'credits_cost' => 0, 'magnite_cost' => 0, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 0, 'icon' => 'Grenade_Axe.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 3, 'name' => 'High Explosive Grenade', 'description' => 'A standard high-explosive grenade with a medium kill radius. Can be used to remove dirt or bugs or both.', 'json_stats' => '{"Area Damage": 130, "AoE Radius": "4.3m", "Armor Breaking": "300%", "Fear Factor": "100%", "Carried Amount": 4}', 'credits_cost' => 1200, 'magnite_cost' => 0, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 10, 'icon' => 'Grenade_he.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 3, 'name' => 'Neurotoxin Grenade', 'description' => 'Releases a cloud of slow-acting toxins engineered to exclusively affect life indigenous to Hoxxes IV. WARNING: HIGHLY FLAMMABLE!', 'json_stats' => '{"Cloud Radius": "7.5m", "DoT DPS": 12, "DoT Duration": "30s", "Carried Amount": 4}', 'credits_cost' => 3400, 'magnite_cost' => 0, 'bismor_cost' => 20, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 0, 'icon' => 'Grenade_neurotoxin.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 1, 'name' => 'L.U.R.E.', 'description' => 'This Laser Utility Refraction Emitter - or L.U.R.E for short - projects a handsome hologram that will attract all nearby enemies. Be mindful to keep your distance - once the onboard shielding fails, it will unleash a devastating electrical charge.', 'json_stats' => '{"Duration": "20s", "Hologram Health": 50, "Carried Amount": 4}', 'credits_cost' => 0, 'magnite_cost' => 0, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 0, 'icon' => 'Grenade_lure.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 1, 'name' => 'Plasma Burster', 'description' => 'The Plasma Burster does more or less what you\'d expect from the name. It releases 4 bursts of scorching plasma in rapid succession upon being thrown. Keep away from beards at all costs.', 'json_stats' => '{"Number of Bursts": 4, "Burst Area Damage": 60, "Burst AoE Radius": "3.5m", "Carried Amount": 4}', 'credits_cost' => 1200, 'magnite_cost' => 0, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 10, 'icon' => 'Grenade_plasma.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 1, 'name' => 'Proximity Mine', 'description' => 'A timeless classic. Sticks to any surface and explodes shortly after an enemy enters its trigger area. And if it fails to find a target, it can be safely disarmed and retrieved. Note: proximity trigger requires a few seconds for calibration.', 'json_stats' => '{"Area Damage": 110, "AoE Radius": "6m", "Arming Time": "3s", "Carried Amount": 4}', 'credits_cost' => 3400, 'magnite_cost' => 0, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 20, 'jadiz_cost' => 0, 'icon' => 'Grenade_proximity.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 4, 'name' => 'Sticky Grenade', 'description' => 'Will stick to any surface or creature, and then explode after a short time. Sometimes keeping it simple is best.', 'json_stats' => '{"Area Damage": 130, "AoE Radius": "4m", "Impact Fear Factor": "250%", "Explosion Fear Factor": "100%", "Carried Amount": 6}', 'credits_cost' => 0, 'magnite_cost' => 0, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 0, 'icon' => 'Grenade_sticky.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 4, 'name' => 'Incendiary Grenade', 'description' => 'One of our most popular "handle with care" items. Will explode on activation, covering a large area in roaring fire. Would almost be cozy if the flames did not burn hot enough to melt steel.', 'json_stats' => '{"Damage Radius": "4.3m", "Carried Amount": 4}', 'credits_cost' => 1200, 'magnite_cost' => 10, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 0, 'icon' => 'Grenade_incendiary.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 4, 'name' => 'Cluster Grenade', 'description' => 'When one grenade just won\'t cut it. This thing is basically Armageddon in the palm of your hand.', 'json_stats' => '{"Bomblets": 9, "Bomblet Area Damage": 40, "Bomblet AoE Radius": "3.8m", "Bomblet Stun Chance": "50%", "Bomblet Stun Duration": 1.5, "Carried Amount": 4}', 'credits_cost' => 3400, 'magnite_cost' => 0, 'bismor_cost' => 0, 'umanite_cost' => 20, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 0, 'icon' => 'Grenade_cluster.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 2, 'name' => 'Inhibitor-Field Generator', 'description' => 'The IFG - or Inhibitor-Field Generator - is one of the latest inventions of the good people down in R&D. Toss one of these bad boys into a cluster of bugs, and watch them slow right down. Enemies affected by the IFG field also take amplified damage from all sources.', 'json_stats' => '{"Slowdown Strength": "75%", "Damage Amplification": "x1.3", "Field Radius": "3.4m", "Duration": "20s", "Carried Amount": 6}', 'credits_cost' => 0, 'magnite_cost' => 0, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 0, 'icon' => 'Grenade_ifg.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 2, 'name' => 'Cryo Grenade', 'description' => 'Instantly lowers the ambient temperature of everything in a medium-sized area. Will flash-freeze most Hoxxes wildlife - as well as any helpless DRG employees caught in the blast zone.', 'json_stats' => '{"AoE Radius": "6m", "Carried Amount": 4}', 'credits_cost' => 1200, 'magnite_cost' => 10, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 0, 'enor_pearl_cost' => 0, 'jadiz_cost' => 0, 'icon' => 'Grenade_freeze.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
           ['character_id' => 2, 'name' => 'Pheromone Canister', 'description' => 'Any creature covered by the substance within becomes an irresistible target to any kind of Hoxxes wildlife. Handle with extreme care. The boys in R&D are very proud of this one.', 'json_stats' => '{"AoE Radius": "6m", "Carried Amount": 4}', 'credits_cost' => 3400, 'magnite_cost' => 0, 'bismor_cost' => 0, 'umanite_cost' => 0, 'croppa_cost' => 20, 'enor_pearl_cost' => 0, 'jadiz_cost' => 0, 'icon' => 'Grenade_pheromone.png', 'patch_id' => 5, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
        ];
        Throwable::insert($throwables);
    }
}
